name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JOBLYTICS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.JOBLYTICS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean via SSH
        run: |-
          ssh root@${{ secrets.JOBLYTICS_HOST}} << 'EOF'
          cd /root/joblytics
          git pull origin main
          docker-compose down
          docker-compose up --build -d
          EOF
